### ISSUE TITLE
Add Printing Support

### ISSUE THREAD

**Issue by 9000-volts** [atom-community/markdown-preview-plus#114]
An option to export the document to PDF, or print it, would be immensely useful.
A fork of this project, [markdown-preview-katex](/abejfehr/markdown-preview-katex), already supports these to some extent, although the implementation seems a bit buggy.

All you have to do is right-click on the preview window, and click `Save as PDF`. On windows, this opens up a print dialog, where the user can either directly print the document or export it properly as PDF.

I think it would be better to separate this into two context-menu options, `Print`, and `Save as PDF`, instead. The behavior could be as follows:
- `Print` would open a print dialog, as `Save as PDF` does currently, and
- `Export PDF` would open up a save-file window to save the PDF somewhere.

**EDIT**

The plugin is atom-markdown-katex, not markdown-preview-katex.

**Comment by Galadirith** [comment]
@htmlguy Thanks again for your input.

I have tried out `markdown-preview-katex` and I actually don't see the `Save as PDF` option when I right-click. I've also searched the code in their repository and the only reference I can find to PDF's is in the `README` under [**Saving as PDF**](https://github.com/abejfehr/markdown-preview-katex/blob/70dad625e69769a385c1bf70d9f8bc6dede35b7a/README.md#saving-as-pdf). Are you certain its `markdown-preview-katex`?

> An option to export the document to PDF

We are actually already focused on implementing PDF support for our next release `2.2.0`. But instead of adding explicit PDF support to MPP, once we've implemented the relevant changes to our code we will open a PR to @travs awesome `markdown-pdf`. By depending on a dedicated PDF export package this should help minimise the buggy behaviour that you currently experience.

@veltall already requested this in #34 (which is now spun off it to #55, #56 and #57) and also over on travs/markdown-pdf#48.

> or print it

That's an interesting feature. We'll investigate that, but its probably not a feature we could add in our `2.2.0` release.

Thanks @htmlguy

**Comment by htmlguy** [comment]
I am sure it is a feature of markdown-preview-katex. It only appears in the context menu of that window.
![mdpkatex](https://cloud.githubusercontent.com/assets/1672106/9876182/250cdbc4-5b82-11e5-93f5-6c596e6a7b3f.png)

**Comment by Galadirith** [comment]
Thanks for the screenshot @htmlguy really helpful. After uninstalling and reinstalling `markdown-preview-katex` I still don't get it, strange. Would you mind running `apm list -i` and posting the result here, thanks @htmlguy

**Comment by htmlguy** [comment]
Sorry, @Galadirith - I confused the plugin with [atom-markdown-katex](/shd101wyy/atom-markdown-katex).

**Comment by Galadirith** [comment]
@htmlguy no problem, thanks for clarifying that.
