### ISSUE TITLE
Support pandocs `--css`

### ISSUE THREAD

**Issue by branden-akana** [atom-community/markdown-preview-plus#117]
Seems as though the CSS that this package gives Pandoc (the one based off my syntax colors) has the final say, as trying to change it with the `-c <file>` or `--css=<file>` flags via the `Pandoc Options: Commandline Arguments` field in the package options doesn't change its output looks.

Could maybe add it in as a package option or allow the `-c`/`--css` flags?

The CSS I tried to set it to was from here: https://gist.github.com/ryangray/1882525#file-buttondown-css

Someone suggested on [this issue](https://github.com/atom/markdown-preview/issues/70) on `markdown-preview` that users should be able to set a custom CSS (not with Pandoc), so maybe this is worth looking into on that end as well?

(To piggyback off of this issue, how does one achieve [the style](https://raw.githubusercontent.com/Galadirith/markdown-preview-plus/master/imgs/mpp-full-res-invert.png) that was shown on the README.md?)

**Comment by theoctopod** [comment]
So I took a look through the code and realized that the preview is using a .less file which I'm assuming is because it's rendered through Atom so I'd like to note that doing a right-click->`Save as HTML...` didn't make Pandoc use the given CSS either.

**Comment by leipert** [comment]
Yeah, will definitely look into that. Seems related to https://github.com/Galadirith/markdown-preview-plus/issues/102.

I think pandoc needs to render with the `--standalone` option for `--css`. We do not use `--standalone` at the moment and therefore the css file is included. You could try adding the `--standalone` parameter as a temporal workaround.

The only problem could be, that your stylesheet also overwrites atoms styles: https://github.com/atom/markdown-preview/issues/276

**Comment by theoctopod** [comment]
@leipert I recently reinstalled Atom, so my stylesheet is just the default.

**Comment by Galadirith** [comment]
@theoctopod @leipert  I'm really sorry I don't have the time to give some more constructive comment right now, but just to say a little bit.

1. You *could* place https://gist.github.com/ryangray/1882525#file-buttondown-css in [your stylesheet](https://atom.io/docs/v0.186.0/customizing-atom#stylesless) and just wrap those styles in a `.markdown-preview` selector. But there are a lot of competing styles and unless you set lots of things like borders, margins etc the styles described by this stylesheet aren't fully respected that well having tried it myself. Even replacing the styles in our default styles in [`markdown-preview.less`](https://github.com/Galadirith/markdown-preview-plus/blob/563df8743bf57f0bcb12eba0bd0042e202522495/styles/markdown-preview.less) doesn't get any closer to the true style its describing.

   I've already been discussing in #112 the issue of saving HTML with the right CSS and more generally about user customizable CSS in https://github.com/Galadirith/markdown-preview-plus/issues/115#issuecomment-140370326.

   Saving styles shouldn't be a big problem, we just need to make sure we select the correct ones. Custom styles though is a tough one, but my thought's are that we're probably going to need to look into using the shadow DOM to really nail this issue.

2. > How does one achieve the style that was shown on the README.md?

   So this was just me messing around with style because I wanted a nice clean `README` image :D The editor styles are actually a lie, I did them in Gimp as a post process, sorry. But the markdown styles are real :D. They are not well tested but if you would like to give them a run I've posted them to a gist https://gist.github.com/Galadirith/41d261be2c890e7c2f31.

**Comment by SHEscher** [comment]
Hi, I like the default style for markdown to html via "Save As HTML..." a lot. Is there a way to provide  this style in form of a _*.css_ file, such that I can apply it with `pandoc -c ...`?

**Comment by lierdakil** [comment]
Just copy style definitions from exported HTML to a css file I guess. Can't really suggest anything better.
