### ISSUE TITLE
Sync preview window with active Markdown file

### ISSUE THREAD

**Issue by spye** [atom-community/markdown-preview-plus#137]
It would be excellent if it supported the ability to (a) have only one preview tab, rather than multiple tabs, and (b) automatically display the preview of the markdown file that currently has focus. If I open two markdown files, I have to open a preview tab for each file, and when I toggle between the two files, I also need to toggle between the two previews. I'd love to see the preview simply sync with the actively-edited markdown file instead. But I'd like that to be an option, so that those who prefer the multi-tabbed layout can leave that enabled as well.

**Comment by leipert** [comment]
Good idea. @Galadirith, what do you think?

**Comment by Galadirith** [comment]
@spye Thanks so much for you suggestion.

So for (a), while in theory that would be possible, MPP is set up such that quite a lot of the logic for each preview is isolated from each other (in a MVVM pattern). It would require quite a big reorganization of the code and I suspect would have other consequences that I can't think of right now. I hate having to say no to feature requests, but in this case I'm afraid I would have to say we wouldn't be able to implement that.

BUT with for (b), that is definitely possible, with an option as you suggest, that could fit in really nicely and provide an extra bit of of a better user experience.

@leipert and I need to review all the features/fix's for our up coming releases and decided on some release dates, but when we have a target date to release MPP with (b) implement I'll make sure to update you.

Thanks again @spye.

**Comment by spye** [comment]
@Galadirith Thanks for the response! Regarding (a), I fully understand that. That pattern makes sense. If you are able to implement (b) though, I think that would more than compensate for not having (a). When I'm writing things like API documentation, I'm often toggling between three or four active .md files, and maintaining the preview was getting tedious. However, if I only need to open the preview once and then just switch between .md files and the preview will switch as well, that would promote a much more streamlined workflow. I took to using MacDown as an alternative (OS X app), but the limitation is that it doesn't benefit from Atom's folder/project navigation.

Thanks for considering the idea!

**Comment by Galadirith** [comment]
@spye Thanks so much for you patience on this issue. I've preliminarily set a release date for this as 13.12.2015. I'll make sure to keep you updated, thanks again @spye.

**Comment by oliche** [comment]
A quick fix for me has been to add a keyboard binding in the keymaps file: 
```
  'ctrl-S': 'markdown-preview-plus:sync-preview'
```
Just a suggestion and it's not mutually exclusive with the two options above.

**Comment by OJFord** [comment]
Have you all seen [@mark-hahn/markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync)?

It's far from perfect, but much better than nothing.

I'd also suggest that it would be better to form a cohesive effort for a single good scroll synchronisation package that could be used in both markdown-preview and markdown-preview-plus, even if it was bundled with the latter from v3.0.0.

**Comment by OJFord** [comment]
I suppose it would be significantly more effort than other methods (because of the re-write required) - but I imagine that if the preview was implemented as 'just another editor pane', with images and LaTeX implemented in [the new block decorations](http://blog.atom.io/2016/02/03/introducing-block-decorations.html), then it would probably be rather easier to implement scroll synchronisation (and Mark's  package may well work too)?

**Comment by Lmaths** [comment]
sync preview is needed.

**Comment by pierregodard** [comment]
@spye (a) and (b) are implemented in the `Markdown Preview Enhanced` package (which also provides optionally the `KaTeX` math rendering engine, yet sadly lacks all the great MPP `pandoc` options for bibliography). It is indeed much more natural when reading/browsing through multiple markdown files to have just one preview tab. 

I also think this would be great as an optional setting, since the multi-tab behavior can also be useful sometime.
