### ISSUE TITLE
Add Another Maintainer

### ISSUE THREAD

**Issue by EntilZha** [atom-community/markdown-preview-plus#175]
First, fantastic package! I use it nearly every day right now and love it.

I was curious since it seems that you are busy @Galadirith, is there another common committer that could be added to maintainers? Looks like there are a lot of issues/PRs with no comments on them.

On that note, I would be interested in implementing a feature that auto-switched the markdown preview to the most recently active markdown tab (right now nothing happens). I would however need some guidance on where I might start.

**Comment by Galadirith** [comment]
@EntilZha Thanks so much for your interest in MPP. I would love to add more maintainers to MPP. @leipert did some phenomenal work on MPP last year, but I have been very busy since the new year and I would imagine the same is true for @leipert.

If you're still interested in implementing this feature I would be glad to discuss this with you, and consider a PR. I'm saddened that I don't have the time I once had to continue to improve MPP but I would love to see others contributing to MPP if people would like to.

Let me know your thoughts.

**Comment by leipert** [comment]
I feel like this could be closed if we add something to the README and maybe as a issue template.
Somewhat linked to #188 and #269.

Maintainers are really needed, as @Galadirith and I am as well.

**Comment by lierdakil** [comment]
I was thinking about adding a big bold "Maintainers needed" in the readme, but didn't get around to it yet. In any case, as long @Galadirith is the only one with control over collaborators, adding maintainers is a *slow* process. That's at least one appealing reason for #269.
