### ISSUE TITLE
"Save as HTML" doesn't respect "Use github.com style"

### ISSUE THREAD

**Issue by hookxs** [atom-community/markdown-preview-plus#195]
When "Use github.com style" is checked in the settings, the preview has white background and dark font regardless of the "dark" them set in atom (which is fine). However, when such preview is exported using _rightclick->save as HTML_, the saved file has dark background and light font as though "use github.com style" weren't checked.

**Comment by cbuschardt** [comment]
A fix for this would be wonderful!

**Comment by oztalha** [comment]
+1

**Comment by mistycheney** [comment]
+1

**Comment by alexantoinefortin** [comment]
+1
The fix is easy, in the saved html file, locate this section:
`<body class='markdown-preview'>`
and replace it by:
`<body class='markdown-preview' data-use-github-style>`

I will work on a fix tonight and submit a pull request. 
If I fail to do that (it would be my first contribution on gitHub), feel free to fix the problem at your convenience.

**Comment by nateGeorge** [comment]
+1
