### ISSUE TITLE
Can you use a latex template with pandoc preview?

### ISSUE THREAD

**Issue by stockphrase** [atom-community/markdown-preview-plus#218]
Hi,

I'd like to be able to view a live preview of a markdown file that I run through a latex template with Pandoc. Is that possible with MPP?

**Comment by kysko** [comment]
Running a markdown file with a latex template through pandoc produces a latex document, to be processed by some *TeX engine (latex, context, etc).
But Atom/MPP previews HTML documents essentially, so you'll be seeing the code itself at most.

You could force MPP to output an html document (with `--to=html` in the argument for pandoc), but that would be a messy mix of html and latex; the internal browser can't interpret latex macros, so it won't do you good.

To preview what your latex templates give you, use your latex engine (texlive, miktex, whatever); you can give a pandoc argument for your latex engine, and force an output to pdf to get a preview in an _external pdf viewer_.

Or use some free online latex editor (e.g. overleaf).

Or you could translate some of the "styles" you put in your latex template into css style in some way, if possible, and put that css as a pandoc option in MPP.

Essentially, MPP is for a quick (html) preview of the contents of your markdown text; I use it because I'm used to pandoc's flavor of markdown.
