### ISSUE TITLE
command line parameters not working correctly

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [atom-community/markdown-preview-plus#229]
When I enter:

```
--table-of-contents --toc-depth=2 --preserve-tabs --chapters --standalone --template=template_book.latex --latex-engine=xelatex
```

into the field for `Pandoc Options: Commandline Arguments` in the settings for this package inside Atom, I get an error message in the preview pane:

```
Pandoc Error:
pandoc exited with code 2: pandoc: option `--table-of-contents' doesn't allow an argument
```

Try pandoc --help for more information.

However, this is exactly what I would use on command line usually, where it works.

**Comment by kysko** [comment]
From the [documentation for MPP](https://github.com/Galadirith/markdown-preview-plus/blob/master/docs/options.md), the arguments must be comma separated.
So try:
`--table-of-contents, --toc-depth=2, --preserve-tabs, --chapters, --standalone, --template=template_book.latex, --latex-engine=xelatex`

**Comment by ZelphirKaltstahl** [comment]
Ah I see, my bad!
Now it renders. However I notice, that in the preview, it simply pastes my whole template, instead of using the declarations in the pandoc template. Could it be that pandoc templates are not supported?

For example:

> % BETTER ERROR MESSAGES \errorcontextlines 10000 % DOCUMENT ATTRIBUTES \documentclass[12pt, a4paper, parskip=full, openany, twoside]{book} % 12pt : main font size % a4paper : paper format % parskip=full : ??? % openany : no need for an additional (second) pagebreak after a chapter to move new chapters always to the right page \usepackage[ top=25mm, bottom=25mm, left=25mm, right=25mm, bindingoffset=10mm, heightrounded, ]{geometry} % allow pages to be not filled, to avoid stretching of content \raggedbottom ...............

(My template is way longer than that.)
Is all just copied into the preview and then suddenly the content begins:

> .........Causation
> Causation is the relationship between two variables, which expresses, that a change in one of the variables directly affects the value of the other variable. The change in the first variable is the cause for the change in the second variable.

**Comment by kysko** [comment]
Firstly, the preview is in HTML, so it doesn't care much of the LaTeX preamble that mean nothing to a web browser. This gives you some pseudo-WYSIWYG while you write, before exporting to (Xe)LaTeX/PDF. Usually, once I'm done, I use pandoc manually to export to LaTeX/TeXLive (or MikTeX) (or other formats like `docx`, `rtf`, etc) once all is written/edited to my convenience.

Secondly, usually the templates' contents is usually pasted in the LaTeX as is in the appropriate places, except where specific template options are passed/parsed (usually delimited by `$...$` in the templates). You didn't show the original form of your template, so I don't know if it was processed or just pasted as is without the options parsed. I never checked this, since I never care to load LaTeX-related arguments in MMD, because of the First point just above.

So my suggestion is to use it merely for an (HTML) *preview* of the _**content**_ while you work on it, without LaTeX related stuff (eg templates). Once your markdown document is ready, pandoc it to whatever format you want.

**Comment by ZelphirKaltstahl** [comment]
Ah ok, if it is not rendering a PDF but a HTML that all makes sense. I guess this is easier because Atom is  build on electron.

The process you describe with first writing it and then building the real document manually is already what I do ; ) Only wanted to know if certain things are possible in the preview.

I can show you my template if that is of any help to you, but I guess it would rather make sense, if I wrote some CSS if needed and link that as a parameter for the preview.

**Comment by kysko** [comment]
Depends on what you expect from the preview. If the end result is HTML, it would make sense to link a CSS to see immediate results.

Be careful though: there's a bug in some previewers, including MPP, where some CSS styles might affect not only the previewed document, but also Atom's interface! See [Pandoc CSS affects Atom GUI](https://github.com/Galadirith/markdown-preview-plus/issues/207).
