### ISSUE TITLE
Using pandoc to set one's own CSS... goes wrong

### ISSUE THREAD

**Issue by iherman** [atom-community/markdown-preview-plus#241]
My goal is to use my own CSS in the generated HTML. I tried to use pandoc to generate an HTML5 that would use my own CSS instead of the github one. I have already a setup for pandoc using an html5 template, so I set the following in the preferences:

```
--standalone, --to=html5, --template=/Users/ivan/.pandoc/templates/default.html5
```

where the default template includes the CSS I need.

However, the result was invalid. Essentially, `markdown-preview` generated its own `<head>` and then put the result of pandoc into the `<body>`. Essentially, the `--standalone` was ignored, whilst that is the correct way of setting one's own css via pandoc. Any other approach that would work?

**Comment by lierdakil** [comment]
Problem is, we're essentially rendering a DOM fragment, and then pasting it inside the existing DOM. I can't think of no non-completely-hacky way to insert a complete DOM tree (including `html`) inside a DOM tree... shadow-dom doesn't support `link` tags, so only way to do this would be `webview`, with whole body urlencoded in an attribute, which would be just... sad...

**Comment by kysko** [comment]
@iherman 
even if you don't put `standalone` using `--css` with `pandoc` itself, it will accept it.
Using css options in MPP's pandoc's settings might cause problems though. See #207 
So avoid style on body and other sensitive tags.

@lierdakil 
Why not create a temp html file, like `atom-html-preview` seems to do, instead of a whole ugly url encoded attribute? Any issues, security or otherwise?
Re-writing would be annoying I'm sure though, just to support css cosmetics.

**Comment by lierdakil** [comment]
@kysko, cross-platform compatibility can be a bit of pain, and using temp. files is usually slower than using pipes. Also, on the topic of re-writing, pandoc support is a horrifying mess right now, so that has to be rewritten *at some point*. But whether or not anyone actually finds time to do this in the foreseeable future is an open question...

**Comment by lierdakil** [comment]
P.S. MPP uses some fancy tricks to minimize DOM updates (and DOM is *slow*, so that is a good thing when it works), so this won't work with `webview`, regardless of whether temp. files or pipes are used. This can be a bit of a concern. That said, I can't say from the top off my head if pandoc renderer even uses those fancy tricks, so this might be off the mark completely.

**Comment by lierdakil** [comment]
Closing in favor of #117
