### ISSUE TITLE
Moving to Atom Community

### ISSUE THREAD

**Issue by leipert** [atom-community/markdown-preview-plus#269]
This has been previously discussed publicly in https://github.com/Galadirith/markdown-preview-plus/issues/188#issuecomment-192964272 and privately with @Galadirith and @lierdakil (and some of the atom-community guys 👍 )

I support this move, as MPP could just benefit from the support of a greater community and it prevents MPP to be orphaned.

In the private conversation @Galadirith and @lee-dohm from @atom-community supported this.

@lierdakil: What is your opinion on this matter?

My proposed steps of solving this matter would be:
1.  Get okay of all MPP maintainers (@Galadirith, @lierdakil and @leipert)
    - [x] Galadirith
    - [x] lierdakil 
    - [x] leipert
2.  Add Galadirith to atom community with move rights and [move the d*mn thing](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)
3.   (If Needed) Add original maintainers back to new MPP repo.

What does everyone think?

**Comment by lierdakil** [comment]
I was one who initially suggested this, so I'm more than ok with it. There's a small caveat however: @lee-dohm pointed out that someone will still have to fulfill maintainer role, and since @Galadirith is preoccupied with other things, this would fall to either me or you in any case.

**Comment by leipert** [comment]
I really would love to do it, but my schedule is to full and I am not using Atom/writing markdown that much anymore.

Anyway, as I already threw so much time at MPP (instead of doing my bachelor thesis [which was completely written with MPP and pandoc btw.]) I am more than happy to help with project management, like sorting out issues.
I could also help with the markdown-it and pandoc side of things, but I really do not want to deal with all the Atom/Electron specific stuff.

Where do your interests lie, @lierdakil ? Maybe we could do more of a combined maintainer role

**Comment by lierdakil** [comment]
I sure could use some help with sorting out issues.

As for my interests, and I'm using MPP(+pandoc) for a variety of tasks, from a couple personal bloggy-style websites to writing journal articles.

I'll be fine dealing with pandoc, since I'm [reasonably familiar with it](https://github.com/jgm/pandoc/commits/master?author=lierdakil), and I'm familiar enough with Atom's guts so that it shouldn't be a big problem. Markdown-it, not so much.

The main problem is I'm pretty short on time, and I already have a whole [atom-haskell](https://github.com/atom-haskell) to maintain, so there won't be a lot of input from me in terms of new features and non-critical bugfixes. Basically I can only commit to dealing with things I personally require for my work and looking over PRs. That's not much, but better than nothing. Having a full-time maintainer would be better, but I don't see anyone willing to take on this role at the moment.

**Comment by Galadirith** [comment]
@leipert @lierdakil Thanks for opening the issue so we can discuss this openly.

I very happy and grateful to both of you for taking leading roles with MPP, even if it is not as full-time maintainers. To me almost everything is set to move MPP to @atom-community.

The one (solvable) issue I have is that I am not sure how transferring ownership affects MPP presence on https://atom.io/packages. Specifically how does it affect users who already have MPP installed. Will it automatically redirect/become @Galadirith->@atom-community? Will users have to manually uninstall Galadirith/MPP and reinstall atom-community/MPP? If so how will they know to do this?

Hopefully @lee-dohm might be able to provide some guidance on this. Or perhaps one of @leipert @lierdakil know.

I would preliminarily set the transfer date for this Saturday, but if it can be done sooner that would be great and I would be happy to do so once we've clarified this issue.

**Comment by lee-dohm** [comment]
@Galadirith So long as the repo is transferred using the standard GitHub action in the Settings, everything will automatically redirect and https://atom.io will just work. (There's even [a section in the Atom Flight Manual on this](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership) :grinning:)

**Comment by lierdakil** [comment]
Yep, it will "just work". I should point out that it would probably be a good idea to update repo in `package.json` after moving though. That could be done by anyone with push privileges of course, so that's more of a note to myself.

**Comment by leipert** [comment]
While looking at the package.json:
What is the state of those two dependencies, @Galadirith ?
```
 "MathJax": "https://github.com/Galadirith/MathJax/tarball/2.4.0-electron.0.2.0",
 "markdown-it-math": "https://github.com/Galadirith/markdown-it-math/tarball/fix-table-pipe-parse-no-ascii",
```

**Comment by lierdakil** [comment]
@leipert, good point. Probably a good idea to transfer mathjax-wrapper and MathJax at least, while we're at it...

**Comment by Galadirith** [comment]
@leipert @lierdakil Just to summarise these two dependencies

- **markdown-it-math@fix-table-pipe-parse-no-ascii**
  This was to fix #185 where inline maths would not work inside tables. I never actually made a PR to `markdown-it-math` because it was quite large, but maybe that would be a good idea to do.

- **MathJax@2.4.0-electron.0.2.0**
  This was to create a small bundle of MathJax with only the parts required by MPP. Its possible that at this point KaTeX is mature enough (I haven't checked recently) to replace MathJax+Diff Engine in MPP. But that is probably an unnecessary amount of work for something that isn't broken.

Neither of these should need to change but I would be more than happy to transfer these as well. If @atom-community don't want multiple packages related to MPP then I could also transfer them to either of you.

**Comment by Galadirith** [comment]
> There's even [a section in the Atom Flight Manual on this](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership) :grinning:

@lee-dohm Thanks so much for the reference, I should have checked the Flight Manual, I haven't look at that since the very beginning :D

I'm happy with everything now. @lee-dohm I did attempt to transfer to @atom-community but as @leipert pointed out this didn't work because I'm not a member. Could you please add me as a member so that I can transfer it. Or if there is another transfer strategy that you could suggest I would be more than happy to follow that (ie transfer to @lee-dohm to then transfer to @atom-community) Thanks :D

**Comment by lee-dohm** [comment]
@Galadirith I made you a member. Let me know if you have any other questions or needs :+1:

**Comment by lee-dohm** [comment]
> If @atom-community don't want multiple packages related to MPP then I could also transfer them to either of you.

Moving these to atom-community also shouldn't be a problem.

**Comment by Galadirith** [comment]
> @Galadirith I made you a member

Thanks so much. I still cannot transfer to @atom-community as I don't have permissions to create repos. If it isn't possible to be granted those permissions I would still be happy to do an intermediate transfer to you or anyone else who does have permission to create repos in @atom-community.

@lee-dohm thanks so much for all your support on this I really appreciate it.

**Comment by lee-dohm** [comment]
@Galadirith I've temporarily given you access to create repositories. Please let me know when the transfer process is complete so that I can restore things to normal :grinning:

**Comment by Galadirith** [comment]
@lee-dohm Thanks so much.

I have transfered the three repositories

- markdown-preview-plus
- MathJax
- mathdown-it-math

I also created a maintainer team for markdown-preview-plus (https://github.com/orgs/atom-community/teams/markdown-preview-plus), however I cannot add markdown-preview-plus to that team to allow write access to MPP. Hopefully thats something you would be able to fix.

I'd suggest that @leipert and @lierdakil request to join that team.

Please feel free to revoke my access to create repositories within @atom-community. Thanks again @lee-dohm 😄

**Comment by lee-dohm** [comment]
@Galadirith I have:

1. revoked your access to create repositories
1. added the atom-community/markdown-preview-plus team to all three repositories and granted admin access to those three repositories for that team
1. sent invitations to @leipert and @lierdakil to join the team

**Comment by Galadirith** [comment]
@lee-dohm Thanks so much for all the time you've spent helping us with this.

**Comment by lee-dohm** [comment]
You're all very welcome. I'm glad I could help!

**Comment by lierdakil** [comment]
I've updated references in `package.json` and `README.md`. Note that I had to move AppVeyor CI to my account, since it got confused by the move. I believe this concludes the move, for the most part, so I believe it's reasonable to close this.

Thanks everyone!
