### ISSUE TITLE
The theme UI bugs of "code blocks"?

### ISSUE THREAD

**Issue by danche354** [atom-community/markdown-preview-plus#306]
1. When I insert `code block` in to the markdown file and after I previewing it in new panel, the highlight is strange and I cannot see some codes, like following
![2017-09-07 10 40 08](https://user-images.githubusercontent.com/11846497/30169306-9fd273ec-941e-11e7-9ea5-af26c98a4874.png)

2. Also occurred when I insert `cpp` code blocks into the markdown file, the `{}` and `<<` marks changes the fonts color. Is this some bugs?
![2017-09-07 10 46 18](https://user-images.githubusercontent.com/11846497/30169435-fb596dd8-941e-11e7-8eb1-dd0909f6b4f3.png)

**Comment by lierdakil** [comment]
Highlighting really isn't something we're really responsible for, especially in editor. So for the latter problem, file an issue on Markdown grammar package you're using. IIRC there are a lot of corner cases with runaway scopes in CPP grammar, so that's something to consider.

As for colors in preview, that depends mostly on your Atom/syntax theme I believe. It's somewhat strange that you apparently have dark syntax theme and preview shows light grey editor though. Make sure you disabled `markdown-preview` package (which is bundled with Atom and conflicts with markdown-preview-plus).

**Comment by lierdakil** [comment]
ETIMEDOUT
