### ISSUE TITLE
Pandoc citeproc

### ISSUE THREAD

**Issue by gpetrini** [atom-community/markdown-preview-plus#325]
Hi, I'm starting with atom and Markdown. I don't how to configure the package to run pandoc citeproc. I've tried every single way to change the settings and it does not work. There are some printscreens below:

![image](https://user-images.githubusercontent.com/34845115/34345080-48375430-e9d3-11e7-8e86-b43bb0f96761.png)
![image](https://user-images.githubusercontent.com/34845115/34345083-506475fc-e9d3-11e7-8d22-b35ca4224170.png)

In addition, when I use pandoc in cmd it runs ok, but when I use atom, none of my quotations are correct.

How can I solve this problem?
Tks

PS I'm using the pandoc-convert package too
PSS It is my first question in github

**Comment by lierdakil** [comment]
Enable the 'Enable Pandoc Parser' option, otherwise MPP doesn't use Pandoc at all. In addition, 'Pandoc Options: Citations' adds pandoc-crossref as a filter, and additionally enables other bibliography-related options. If you just want citations with bibliography and csl specified in document YAML metadata, adding `--filter pandoc-citeproc` to options is a more straightforward option.
