### ISSUE TITLE
Some uppercase greek symbols are not recognized

### ISSUE THREAD

**Issue by murpholinox** [atom-community/markdown-preview-plus#336]
For example this 
```
\[
 \Epsilon \epsilon \Alpha \alpha \Beta \beta \Gamma \gamma \Omega \omega
\]
```
gives
![screenshot from 2018-01-15 20-30-31](https://user-images.githubusercontent.com/732802/34969151-ff8bf6d0-fa32-11e7-83e9-76c5537b3aa8.png)

**Comment by lierdakil** [comment]
[LaTeX doesn't define *all*](http://latex.wikia.com/wiki/List_of_LaTeX_symbols) of the uppercase Greek letters, because those would look *exactly* like Latin:

For reference,

No special math mode symbols:
- o ⇒ O

Only lowercase mathmode symbols:
- α `\alpha` ⇒ A
- β `\beta` ⇒ B
- ε `\epsilon` ⇒ E
- ζ `\zeta` ⇒ Z
- η `\eta` ⇒ H
- ι `\iota` ⇒ I
- κ `\kappa` ⇒ K
- μ `\mu` ⇒ M
- ν `\nu` ⇒ N
- ρ `\rho` ⇒ P
- τ `\tau` ⇒ T
- χ `\chi` ⇒ X

Lowercase and uppercase mathmode symbols:
- γ `\gamma` ⇒ Γ `\Gamma`
- δ `\delta` ⇒ Δ `\Delta`
- θ `\theta` ⇒ Θ `\Theta`
- λ `\lambda` ⇒ Λ `\Lambda`
- ξ `\xi` ⇒ Ξ `\Xi`
- π `\pi` ⇒ Π `\Pi`
- σ `\sigma` ⇒ Σ `\Sigma`
- υ `\upsilon` ⇒ Υ `\Upsilon` (depending on the font, it's less like Y, e.g. ![picture of rendered mathmode Upsilon](https://user-images.githubusercontent.com/7275622/34972485-ebae6e26-fa92-11e7-9e1f-ec4338ba0f92.png))
- φ `\phi` ⇒ Φ `\Phi`
- ψ `\psi` ⇒ Ψ `\Psi`
- ω `\omega` ⇒ Ω `\Omega`

Define the commands yourself if you need to:
```latex
\newcommand\Alpha{\mathrm{A}}
\newcommand\Beta{\mathrm{B}}
\newcommand\Epsilon{\mathrm{E}}
\newcommand\Zeta{\mathrm{Z}}
\newcommand\Eta{\mathrm{H}}
\newcommand\Iota{\mathrm{I}}
\newcommand\Kappa{\mathrm{K}}
\newcommand\Mu{\mathrm{M}}
\newcommand\Nu{\mathrm{N}}
\newcommand\Rho{\mathrm{P}}
\newcommand\Tau{\mathrm{T}}
\newcommand\Chi{\mathrm{X}}
```

See [docs on global macro definitions](https://github.com/atom-community/markdown-preview-plus/blob/master/docs/math.md#macros)

```cson
Alpha: "\\mathrm{A}"
Beta: "\\mathrm{B}"
Epsilon: "\\mathrm{E}"
Zeta: "\\mathrm{Z}"
Eta: "\\mathrm{H}"
Iota: "\\mathrm{I}"
Kappa: "\\mathrm{K}"
Mu: "\\mathrm{M}"
Nu: "\\mathrm{N}"
Rho: "\\mathrm{P}"
Tau: "\\mathrm{T}"
Chi: "\\mathrm{X}"
```

**Comment by murpholinox** [comment]
You are right! I am so dumb!
As an excuse I can say that I have not slept much

**Comment by lierdakil** [comment]
Happens to all of us. No harm done.
