### ISSUE TITLE
Are custom file-extensions working for markdown preview files?

### ISSUE THREAD

**Issue by jlperla** [atom-community/markdown-preview-plus#349]
I am using some Julia https://github.com/mpastell/Weave.jl files, which are markdown with embedded code and have the `.jmd` extension.

I tried to go into the markdown-preview-plus and did the following: 
- Changed the `Markdown file extensions` to `markdown, md, mdown, mkd, mkdown, ron, txt, jmd`
- Turned on `Enable Math Rendering By Default`
-Closed the settings tab

But after doing that, restarting Atom, etc.  The preview window will not open.  If I copy the same code and rename it to a `.md` extension, then no problem with the preview.

I also have the https://atom.io/packages/language-weave extension installed, but not sure why that would break the extensiosn

**Comment by lierdakil** [comment]
Okay, a bit of a background, which might be not entirely obvious to those less familiar with Atom's internal workings.

So MPP can display preview one of two ways:

1.  it can show the preview of the currently-open file
2.  it can show the preview of a file on disk (via 'Markdown Preview' context menu item in file tree view -- [here's a screenshot for reference](https://user-images.githubusercontent.com/7275622/36457485-446b4734-16bb-11e8-8407-b343c2cb169a.png))

To determine if it should work in the first case (and by "work" I mean "provide the command to toggle preview") it looks at the currently-selected grammar in active editor. So you need to tweak 'Grammars' setting if you're using non-standard Markdown grammar. Run `editor:log-cursor-scope` command on an editor using the grammar you want -- the top line in the message is the root scope, which you can add to 'Grammars', and everything should work.

In the second case, since the file isn't necessarily open, there's no grammar to speak of. So it looks at the file extension to decide if it should provide 'Markdown Preview' context menu item.

**Comment by jlperla** [comment]
Thank you, it works beautifully with the `source.weave.md` grammar.

Is there any way you could add the `.jmd` to the default list of file type and the `source.weave.md` to the default list of markdown grammars?

**Comment by lierdakil** [comment]
TBH, the default list is a bit of a can of worms, so I'm rather reluctant to touch it. Adding every Markdown grammar under the sun (and there are quite a few of those) to the default values and *maintaining that list* is far beyond our capabilities. That was the point of making it configurable in the first place.

I hate to make it into a popularity contest, but `language-weave` doesn't seem to be wide-spread enough for its inclusion to be worth it.

**Comment by jlperla** [comment]
I understand.  Hopefully at some point the number of Julia users is high enough to win a popularity contest!
