### ISSUE TITLE
Stylesheet not applied

### ISSUE THREAD

**Issue by GafferMan** [atom-community/markdown-preview-plus#358]
I have been using Atom for awhile for documentation development. I use Markdown-Preview-Plus with pandoc to render my markdown inside of Atom. It used to apply my Stylesheet (styles.less), but that just stopped working recently. Even without using pandoc, styles are not applied.

I even tried removing all .markdown-preview styles and just adding a backgorund-color. That didn't work either.

I'm at a loss as to how to troubleshoot this issue further.

Thank you.

**Comment by lierdakil** [comment]
Yeah, sorry. I've changed the layout somewhat since the old one was inherited from bundled markdown-preview and it created some problems.

Use `markdown-preview-plus-view` element selector instead, f. ex.:
```css
markdown-preview-plus-view {
  background-color: red !important;
}
```

A fair warning though, due to how CSS works, you *might* need `!important` qualifier, or make the selector more specific with either `markdown-preview-plus-view:not([data-use-github-style])` or `markdown-preview-plus-view[data-use-github-style]`, depending on whether you're using GitHub style overrides or not (or if you don't want to concern yourself with that, `markdown-preview-plus-view.native-key-bindings` should work too)

**Comment by GafferMan** [comment]
Thank you!
