### ISSUE TITLE
Relative file paths are rendered in HTML as absolute file paths

### ISSUE THREAD

**Issue by nullrend** [atom-community/markdown-preview-plus#365]
Currently using this plugin to write documentation for our software platform. The source text is written in Markdown, rendered into HTML and then uploaded to Zendesk. This plugin is tremendously useful for it, thank you so very much! There is just an issue when rendering Markdown images into HTML that is giving me a bit of grief.

On Windows, Markdown for images like 

```
![image](/hc/article_attachments/0000000000/image.png]
```

will render in HTML as

```
<img src="C:\Users\USERPROFILE\hc\article_attachments\00000000000\FILE" alt="FILENAME.PNG">
```

- The relative path will change into an absolute path.
- Forward slashes will turn into backslashes.
- This does not happen for regular links.

This necessitates editing the rendered image URL manually to have it match the location of the file in Zendesk and switching the backslashes into slashes. I looked at editing the JS files involved in the rendering code but my JS isn't good enough to figure out the routines determining this behavior.

Would it be possible to have the package keep the relative path the same or at least provide an option to switch between relative paths and absolute paths?

**Comment by lierdakil** [comment]
Okay, so the code responsible is in
https://github.com/atom-community/markdown-preview-plus/blob/2728674cf637d4d17eec0b26268afd210a959fd5/lib/renderer.js#L118-L138

You can most likely get away with conditionally disabling https://github.com/atom-community/markdown-preview-plus/blob/2728674cf637d4d17eec0b26268afd210a959fd5/lib/renderer.js#L51 from here: https://github.com/atom-community/markdown-preview-plus/blob/2728674cf637d4d17eec0b26268afd210a959fd5/lib/renderer.js#L28

However, this might not necessarily be what people would want, in general. A more robust approach could be to relativize image paths on save.

I don't have much time to dedicate to this currently, due to being somewhat swamped with other work and a big project going on with this package in the background (#363 for one). So I can't promise a speedy fix.

To be perfectly honest, I don't think this package is all that well suited for Markdown-to-HTML convertsion. Maybe consider using something like [Pandoc](http://pandoc.org) directly instead?

**Comment by nullrend** [comment]
Totally missed your response. I'll give the code you posted a try and see what the results are. Copying to HTML saves me a couple of steps in getting the text from a markdown file into Zendesk as HTML but I never really thought of using pandoc on its own; I should really look into that.

**Comment by lierdakil** [comment]
Got around to working on this a bit. If you could take a quick look at PR #380 and comment whether or not it would cover your use-case, that would be nice. Thanks.
