### ISSUE TITLE
Preview doesn't honor editor font set from "fonts" Atom package

### ISSUE THREAD

**Issue by kylebarron** [atom-community/markdown-preview-plus#402]
**Edit:** It's fixed for me by adding `Fira Code` to the `Font Family` option under Editor Settings instead of using the code provided by the `fonts` package, but I'll leave this open in case you guys want to try to fix the interaction with the `fonts` package. (It does have 160k downloads).

Otherwise feel free to close.

---

![image](https://user-images.githubusercontent.com/15164633/41050095-6c175e90-6980-11e8-8f01-b8e1734dcfc0.png)

I'm using a monospaced font in the editor, so I'm surprised that the font in the code blocks is not monospaced. It's rare in general to use a non-monospaced font for code.

This works correctly when "Use native Pandoc code block style" is checked.

---

It turns out this happens only when the [`fonts`](https://github.com/braver/fonts) package is active. 

![image](https://user-images.githubusercontent.com/15164633/41050244-c9134bcc-6980-11e8-93dc-8ab7117c0177.png)

![image](https://user-images.githubusercontent.com/15164633/41050251-cfc9e8a4-6980-11e8-9b22-e6ddf63c1734.png)

I use the Fira Code font from that package.

**Comment by lierdakil** [comment]
It would be rather hard and honestly pretty pointless to try to fix this on our side, because the way `fonts` does things is... let's call it "suboptimal".

If `fonts` injected its styles via `atom.styles.addStyleElement`, as is intended in Atom more or less, instead of hacking a variable into the `style` attribute on `body` element, it would most likely work out of the box. I might consider creating a PR doing that and fixing a few other messed-up things I noticed during a cursory look at the code, but I don't have all that much time on my hands right now, so that might take a while.

@braver, any particular reason `fonts` sets `style` on `body` element instead of injecting a `style` element via `atom.styles.addStyleElement`? Also, would you be interested in the PR alluded to above?
