### ISSUE TITLE
Allow setting for which directory Pandoc is run from

### ISSUE THREAD

**Issue by kylebarron** [atom-community/markdown-preview-plus#410]
I use a top-level Makefile to create documents through Pandoc, so I often run something like
```
pandoc ./src/file.md ./pdf/output.pdf
```

But this causes Pandoc to resolve relative links from the top of the directory, not from inside `./src/`, so if I want to link to `./img/image.png`, the text in `file.md` should be
```
![](img/image.png)
```
and not
```
![](../img/image.png)
```

It seems that this package always invokes Pandoc from the location of the viewed file. Is it possible to add a setting for invoking Pandoc from the project directory? Like Hydrogen:
![image](https://user-images.githubusercontent.com/15164633/41802423-950d5cf2-764e-11e8-8b17-6b176f507fc1.png)

The code from Hydrogen looks pretty simple, so I imagine it would be easy to implement here:

https://github.com/nteract/hydrogen/blob/dc9a65f6dc35fc87b8be61b6b1fcc33d3024d98a/lib/kernel-manager.js#L67-L80

**Comment by lierdakil** [comment]
The issue is not the run directory. When outputting HTML, Pandoc doesn't touch image paths at all. Consequently, MPP has to resolve those on its own -- which it does as it would for any HTML: relative media paths are interpreted as being relative to the file being previewed; "absolute" paths (i.e. starting with `/`) are resolved relative to the project root directory. Doing something else seems highly counter-intuitive.

Pandoc has `--resource-path` option, which allows you to specify where it should look for media files. Perhaps you could use that?
