### ISSUE TITLE
Last table row does not respect alignment when rendering

### ISSUE THREAD

**Issue by levantis** [atom-community/markdown-preview-plus#42]
The following table illustrates this:

| Tables | Are | Cool |
| --- | :-: | --: |
| col 3 is | right-aligned | $1600 |
| col 2 is | centered | $12 |
| zebra stripes | are neat | $1 |

**Comment by Galadirith** [comment]
@levantis I'm so sorry I haven't been able to respond sooner.

From your comment I don't understand what you expected the output to be. I would be grateful if you post your source markdown and briefly describe what output you expected and what output you actually got.

Thanks @levantis and hopefully we can get this fixed quickly :D

**Comment by levantis** [comment]
The expected output is provided in the post itself (the table), and I'll quote its Markdown source here.
```Markdown
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```
The output that I got is
![table-preview](https://cloud.githubusercontent.com/assets/438301/8319421/ac885bf6-19dc-11e5-806d-ff520b9f7ca7.png)

**Comment by Galadirith** [comment]
@levantis Thank you so much for being patient on this issue. I've not been able to reproduce the bug. Here are the examples that I used:

**Right aligned**

````markdown
| Tables        | Are           | Cool  |
| ------------- |:-------------:|------:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
````

produced the following preview:

![table-right](https://cloud.githubusercontent.com/assets/1201875/8633696/6c481f9a-27ce-11e5-8f43-391c6e8b13aa.png)

**Center aligned**

````markdown
| Tables        | Are           | Cool  |
| ------------- |:-------------:|:-----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
````

produced the following preview:

![table-center](https://cloud.githubusercontent.com/assets/1201875/8633702/bf824c58-27ce-11e5-915a-fd96b19d887a.png)

**Left aligned**

````markdown
| Tables        | Are           | Cool  |
| ------------- |:-------------:|:------|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
````

produced the following preview:

![table-left](https://cloud.githubusercontent.com/assets/1201875/8633707/d5ffe4b8-27ce-11e5-8bb8-88a6904c0a7f.png)

I believe its likely another package or your settings may be interfering with the layout. Could I ask you to send me you installed packages (you can run `apm list -i` and copy and paste the results to this issue) and also if you have modified your user style sheet could you post your modifications.

There is a related bug that I discovered where if you change the alignment of a table that already has been previewed then the alignment will NOT change in the preview. A workaround for this is to close and then re-open the preview. I don't believe this is the cause of your problems but it may be worth bearing in mind.

Thanks again for your patience on this @levantis and hopefully we can figure out the root cause soon :D

**Comment by levantis** [comment]
That was the cause of my bug as well - after closing and reopening Markdown preview it was correct!

**Comment by Galadirith** [comment]
@levantis Thanks so much for the update. I'll hopefully be able to correct this behaviour in a future update so you won't have to close and reopen a Markdown preview to get the correct alignment in a table. Thanks again :D
