### ISSUE TITLE
Code blocks appear with light font on GitHub when exporting to a PDF

### ISSUE THREAD

**Issue by Jont828** [atom-community/markdown-preview-plus#425]
When I turn off "render CSS background" and export to a PDF using the GitHub style, the code blocks appear with a light font. The code blocks appear in the preview with white font and a black background, but when I export it with background off, the font doesn't change to black to work with the white background. It, however, does behave properly when I export to HTML. [Here](https://imgur.com/a/iAt5nJm) is an example of what I mean. I tried changing the GitHub styles file in the package, but it only changed the colors on the HTML file, not the preview or the PDF.

**Comment by lierdakil** [comment]
Okay, so this is a bug, which should be fixed. But it's kinda a bug in a way completely opposite of what you expect. That is, exported HTML should (in theory) have the same look as the preview, that is, if you're using the dark colour scheme in Atom, code blocks should also be dark both in HTML export and preview. Due to recent changes to the highlighting code and some CSS shenanigans, it's apparently not.

Disabling CSS backgrounds is purely a Chromium feature and only works in PDF export. It should also darken the text colour, but I guess it depends on the colours in question and perhaps also Atom version. In any case, can't do anything about that one. Try a different highlighting theme perhaps?

I believe I could add a toggle to prefer GitHub style code colour scheme instead of the Atom one. Would that work for you?

**Comment by Jont828** [comment]
Yeah, I tried changing to a light syntax theme and it worked! And yeah, it'd be great if you could add a feature to prefer the GitHub style. Just to make sure I'm understanding this correctly, you mean so the style of code blocks in the preview will be independent of the Atom syntax theme, right? Thanks!

**Comment by lierdakil** [comment]
> style of code blocks in the preview will be independent of the Atom syntax theme

I think I misspoke a bit. Generally, there's no good way to make preview *completely* independent from Atom syntax themes, because you need *some* syntax theme to highlight code. I believe I can make the preview syntax theme independent from *currently active* Atom syntax theme though. This was requested way back in #115, but it was impossible due to both Atom's and MPP's architecture at the time.  It should be possible now.
