### ISSUE TITLE
Add support for LaTeX packages (trees in particular)?

### ISSUE THREAD

**Issue by Jont828** [atom-community/markdown-preview-plus#429]
Is it possible to add support for LaTeX packages? I would like to be able to render automata or trees using the Tikz package. As far as I know, you can't draw trees without importing some package.

**Comment by lierdakil** [comment]
No, sorry. This is not LaTeX. If you want full-blown LaTeX, might as well use it directly. I'm pretty sure there are packages for that too. LaTeX support in MPP is pretty much limited to rendering math.

FWIW, when I had to do something similar, I used embedded SVG. MPP will support that. That said, it only works well if you're targeting HTML specifically, won't really do much good if your intent is ultimately converting it to LaTeX with Pandoc.

**Comment by lierdakil** [comment]
There's a silver lining though. Pandoc supports arbitrary document transformations via filters, so you might be able to convert tikz environments into images using that. Since you're not the first person to think about it, there is some prior art wrt filters, see f.ex. https://github.com/jgm/pandocfilters/blob/master/examples/tikz.py and https://tex.stackexchange.com/questions/431719/how-to-use-pandoc-to-derive-output-from-latex-and-tikz-to-a-docx-file
