### ISSUE TITLE
Pandoc-compatible markdown-it package?

### ISSUE THREAD

**Issue by mb21** [atom-community/markdown-preview-plus#440]
I see you're using `markdown-it` for the preview and trying to make it behave as much as possible as pandoc, correct? There is [this wiki page](https://github.com/atom-community/markdown-preview-plus/wiki/markdown-it-vs.-pandoc), but I cannot find those plugins in the code, or am I looking in the wrong place?

I could see value in creating a js/npm package that does only that: re-export `markdown-it`, configured in such a way to resemble pandoc flavoured markdown as much as possible. I've written [a few lines](https://github.com/mb21/panwriter/blob/master/src/React/Basic/PreviewRenderer.js#L7) as part of [PanWriter](https://github.com/mb21/panwriter), but it's not much yet.

What do you think? Would you people be interested to collaborate on something like that?

**Comment by lierdakil** [comment]
> you're using markdown-it for the preview

Yes, but we also support pandoc separately (although some caveats apply)

> and trying to make it behave as much as possible as pandoc

Not really, no, this never was a goal, at least as far as I am aware. Over the years, a number of plug-ins were added, mostly by user request, so those might have an apparent effect of making markdown-it more pandoc-like, but I believe that's mostly by accident.

A complete list of plugins we currently bundle:
-    markdown-it-emoji
-    markdown-it-imsize
-    markdown-it-lazy-headers
-    markdown-it-table-of-contents
-    markdown-it-task-lists

The reason for markdown-it being there at all is basically having "batteries included". And for many applications, it works just fine, since it's mostly CommonMark-compliant. And when that's not enough, users, myself included, can (and do) install pandoc.

> Would you people be interested to collaborate on something like that?

Sadly, it's just me here at the moment. And to be perfectly honest, I don't see much point in having markdown-it behave like pandoc when you could just as well shell out to pandoc and be done with that.

One place where pandoc is inferior to markdown-it is location synchronization -- but I think it'd be easier to add something like source maps to pandoc rather than trying to hack markdown-it to be more "pandoc-like".

And if you're more interested in portability offered by JS/Node, I'd say it's worth looking into compiling pandoc (or more likely parts of it) with ghcjs -- I believe this was done at one point in https://github.com/osener/markup.rocks

**Comment by mb21** [comment]
Thanks for the quick reply! I see, I guess I was mislead by that wiki page, which was actually created by @leipert.

Thanks for the link to markup.rocks, it is (was) an impressive feat indeed, but performance (i.e. latency) is not too great. Whereas `markdown-it` has plugins for ~95% of pandoc extensions and great performance. I'll see how it goes... if I get it working well, I may still publish a package.

**Comment by mb21** [comment]
I've started a package... just in case other people are interested in contributing:

https://github.com/mb21/markdown-it-pandoc
