### ISSUE TITLE
[Feature request] preview follow cursor

### ISSUE THREAD

**Issue by biocyberman** [atom-community/markdown-preview-plus#455]
I find my self scroll up and down to find the portion of preview that is corresponding to the line/paragraph I am writing. It will be really nice to have the preview follow the cursor.

**Comment by lierdakil** [comment]
Try setting the first two options in the 'Preview position synchronization behaviour' section of the MPP settings?
![Preview position synchronization behaviour settings section with three toggle options visible: 1. Sync preview position when text in editor changes; 2. Sync preview position when text editor is scrolled; 3. Sync editor position when preview is scrolled. The first two are turned on, the third one is turned off.](https://user-images.githubusercontent.com/7275622/55665315-d6b9cf80-5845-11e9-8bd6-20a77bd15f5d.png)

Bear in mind that synchronization works well only with markdown-it renderer, with pandoc it's a bit of a mixed bag, sometimes it works well enough, and sometimes it breaks spectacularly. And by "breaks" I mean "seemingly randomly scrolls to an absolutely unrelated part of the document".

**Comment by JackElsey** [comment]
I came here to ask to this feature for use with Atom on Ubuntu. I realize now that I was using an old version of this package without those settings because `apt-get` was giving me an old version of Atom that was incompatible with the newest version of this package.

I reinstalled Atom via the `.deb` file on their [website](https://atom.io/), and that allowed me to install the latest version of this package with this feature.
