### ISSUE TITLE
preview couldn't be toggled

### ISSUE THREAD

**Issue by ShanwenYan** [atom-community/markdown-preview-plus#467]
Hi I am using Atom version 1.40.1 with Ubuntu system and the package is already updated with markdown-preview disabled. However even when I select toggle under packages nothing happens. I also tried reinstalled but it still doesn't work. Something weird for my computer is that I have blank page when I open keymap. Could anybody kindly help? Thanks!

**Comment by lierdakil** [comment]
Open a Markdown file. Run `markdown preview plus: toggle` command from the command palette (this command is bound to `ctrl+shift+M` by default). If you don't have a Markdown file open in the currently focused text editor (detected by the grammar used), nothing will happen when you run that command. This is done this way to allow you binding other actions to `ctrl+shift+M` for non-Markdown files if you want to. Here's a gif of how this is supposed to work.
![mpp-toggle](https://user-images.githubusercontent.com/7275622/64997930-d80a2080-d8ea-11e9-9371-78892614917c.gif)

>  I have blank page when I open keymap. 

That is by design. Your keymap file is basically list of overrides. When your keymap file is empty, it just means you have no overrides. Refer to Atom Flight Manual for more information on keymaps.

**Comment by ShanwenYan** [comment]
Thank you so much for your quick reply! However I am calling from a .md file. Do you think I should reinstall atom?

**Comment by lierdakil** [comment]
A couple things you can do before trying to reinstall (it rarely helps anyway):
1. You're using a non-standard Markdown grammar that we don't recognize as such. Run `editor: log cursor scope` command on the editor with a Markdown file open to check what grammar it's using.
2. Something might be silently going wrong. Check the developer console for errors. You can do that by running `window: toggle dev tools` command and opening `console` tab.

**Comment by ShanwenYan** [comment]
Adding source code works! Thank you very much!

**Comment by lierdakil** [comment]
Glad I could help. For reference, what grammar are you using?

**Comment by ShanwenYan** [comment]
I am using 'source.gfm.jinja'

**Comment by rwendt-bw** [comment]
I'm having the same issue. 

Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

 rwendt@rwendt-Latitude-7490  ~  dpkg -s atom | grep Version
Version: 1.40.1

I think the issue is related to the Preview Behavior > "Direction to load the preview in split pane" setting.

When I set this to **none**, nothing happens when using ctrl-shift-M or by running the command via the command pallet. 

When I set this to **right** it works properly.

**Comment by lierdakil** [comment]
@rwendt-bw sorry, I missed your comment. The issue you're describing is entirely different from what is discussed here. Furthermore, I can not reproduce the issue you're describing -- when `none` is selected, the preview is opened in the same pane as the editor, which is the expected behaviour.
