### ISSUE TITLE
Open relative links to files from markdown preview

### ISSUE THREAD

**Issue by breschke** [atom-community/markdown-preview-plus#72]
I'd like to be able to write (relative) links to files and open these files in Atom by clicking links in the markdown preview.

**Comment by leipert** [comment]
@Galadirith This is a feature I would love too. I just had a quick look and I think it is something which needs to be handled in the `markdown-preview-view.coffee`.

It is somewhat related to the scroll-sync issue #9 

Related: https://discuss.atom.io/t/how-to-capture-ctrl-click/13985

**Comment by leipert** [comment]
@Galadirith. I just started on the branch feature/open-relative-files, see #73.
What I would love to see now, is the following:

It works really well with this document:
```markdown
[relative](./local.md)

[google](http://google.de)
```

If I am navigating through local documents, open up not only the matching TextEditor, but also the matching Preview. So:

1. Open a file `1.md`. This file contains `[foo](2.md)`.
2. Open Preview for `1.md`
3. Click on link `foo`
4. TextEditor and Preview for `2.md`, it contains `[bar](1.md)`.
5. Click on `bar`
6. TextEditor and Preview for `1.md` get focus.

**Comment by leipert** [comment]
Furthermore I would like a shortcut that allows to focus the preview of the file I am editing. At the moment, I just do `Ctrl-Shit-M` twice to do that.

**Comment by Galadirith** [comment]
@breschke Thanks for the feature request :D

@leipert #73 looks good, I'll add some more comments on the PR but to address your comments I definitely agree that opening a `TextEditor` and preview would be very useful. However I do think it would be contextual (for the case of markdown documents), for example if a user has only opened a preview from the treeview (with no associated `TextEditor`) they may well just want a preview open rather than a `TextEditor` or both.

I haven't thought enough about what would be a good way to solve this, but perhaps the choice should be fore the user and made using modifier keys would work; `click` opens the `TextEditor`, `alt-click` opens a preview, and `shift-click` opens both.

I've spun off #74 to handle the focusing preview shortcut.

**Comment by leipert** [comment]
I would vote against the modifier clicking.

A simple behaviour would be:

1. File A is open as `TextEditor` and `Preview` -> click on link -> File B opens with `TextEditor` and `Preview`
2. File A is open only in `Preview` -> click on link -> File B only opens in `Preview`

**Comment by Galadirith** [comment]
Thats makes a lot of sense giving consistent behaviour without adding more controls, great :D 

I'm happy to continue working on this if you want (you added me as the assignee) but I most likely won't be able to finish this for `2.0.0`. We could bump it to `2.1.0` or if you wanted to take it you could continue working on your PR #73 but I wouldn't want to presume that you've got extra time to spend on this issue.

**Comment by leipert** [comment]
Yeah, let's move it, maybe I have the time, then we will move it to back 2.0.0
