### ISSUE TITLE
On-demand/auto sync for markdown-it backend

### ISSUE THREAD

**Issue by szhorvat** [atom-community/markdown-preview-plus#9]
This is not a bug report, just en enhancement suggestion.

It would be useful to have a feature that makes it easier to find source positions based on the preview position.  If you have used LaTeX, you may be familiar with this (if not, I'll explain in more detail).

One possibility for an UI:

Right click somewhere in the preview, click "Sync" in the upcoming menu.  The the cursor in the source view will be positioned at the corresponding location.  (This is precisely how TeXShop works.)

**Comment by II-Matto** [comment]
Maybe this link is useful: https://atom.io/packages/markdown-scroll-sync

I was wondering if this package can be used with MPP.

**Comment by Galadirith** [comment]
Thanks @II-Matto :D I hadn't seen that package before, when I get a chance I'll take a look at its source. Thanks again :D

**Comment by II-Matto** [comment]
@Galadirith Thanks for your effort of making the great MPP! I am now happy using it :-)

The fun thing is that, since Atom does not handle word wrap of CJK characters well, I am using another editor to edit the markdown file and using Atom with MPP to live preview each save. Haha!

**Comment by mangecoeur** [comment]
Would also like to see this work in MPP (note-there's interest in LaTex if you are writing documents with maths - there's growing interest in using this for academic writing). I didn't look into how you do it now, but in the Minimap module there is a system to just get the scroll position of the current text editor and work with that value. If you set both windows to have the same scroll percentage you should end up in more or less the same place or?

**Comment by Galadirith** [comment]
@mangecoeur Thanks for the comment :D Definitely plan to add this. As I [said earlier](https://github.com/Galadirith/markdown-preview-plus/issues/9#issuecomment-67657428) in the issue my preference would be to implement some sort of on demand sync to give better accuracy rather than automatic scroll distance sync. However most likely we can add both. Would you prefer on demand or auto scrolling?

In fact you can get auto scrolling right now if you don't mind an easy hack on @mark-hahn's [`markdown-scroll-sync`](https://github.com/mark-hahn/markdown-scroll-sync). Just install it as normal and then edit [lib/main.coffee#L20](https://github.com/mark-hahn/markdown-scroll-sync/blob/67886727261fa4d0465ae5529bae7e398726e84b/lib/main.coffee#L20), `markdown-preview` -> `markdown-preview-plus`. Reload Atom, then source and preview should auto scroll sync

![mod-markdown-preview-scroll](https://cloud.githubusercontent.com/assets/1201875/8966770/148d9422-362b-11e5-875d-ab71014fd5bf.gif)
(excuse to test out [LICECap](http://www.cockos.com/licecap/) ;D)

Right now the priority is to migrate to `markdown-it` #47 which will greatly improve the reliability of MPP and fix a few bugs. However an added benefit is that `markdown-it` comes baked in with [source-mapping](https://markdown-it.github.io/markdown-it/#Token.prototype.map), which means implementing an on demand sync between source and preview gets much easier.

I'll keep you posted on this issue but feel free to ping the issue if I havn't updated it in a while :D

**Comment by mangecoeur** [comment]
Source-mapped scrolling sounds awesome - it also occurred to me that if you start adding images a simple distance scroll is not going to work (same goes for Latex, when rendered it can significantly change in size compared to the source). Also thinking you probably want an easy toggle between autoscroll and on-demand scrolling - as to which should be default I have no idea sorry :S

**Comment by mark-hahn** [comment]
>  it also occurred to me that if you start adding images a simple distance
scroll is not going to work

Definitely not.  I went to a s***load of trouble getting it to get
`markdown-scroll-sync` to match as well as It does.  I had to walk the dom
and compare tags.  It still doesn't match the interior of code sections.
It should switch to distance in those for a hybrid approach.

Some things have to "hop" of course.  One line in the source referencing an
image matches the whole size of the image.

The problem is so hard that I suspect the atom core will never support it.


@Edward-Fauchon-Jones: Can you issue a pull-request for your change?  Of
course it should work for all markdown preview packages.

**Comment by chaserhkj** [comment]
Would vote for the idea that both a source-mapped on-demand sync scrolling and an automatic synced scrolling being added to MPP, as the first feature is nice for code-inspection, while the latter one should be a killer feature to work with while writing markdown with live preview. Just see atom/markdown-preview#24, one could get an idea about how popular this feature would be.

Currently using `markdown-scroll-sync` from @mark-hahn with MPP hacks as @Galadirith mentions, looking forward to this feature being added to MPP  :)

**Comment by Galadirith** [comment]
@chaserhkj Thanks for all your interest :D I'll post my thoughts and ideas on automatic synced scrolling later (once we've shipped `2.0.0` later today) but I wasn't aware of atom/markdown-preview#24 so its really great to see the demand for such a feature.

Thank you so much for implementing the changes I suggest for [`markdown-scroll-sync`](https://github.com/mark-hahn/markdown-scroll-sync). Something I should have made more publicly clear is that we're migrating to [`markdown-it`](https://github.com/markdown-it/markdown-it) in `2.0.0` which may break those changes, although I haven't had time to verify that.

If you are running our bleeding edge commits from `master` rather than just `1.7.0` you could test to see how it performs.

Thanks again @chaserhkj :D

**Comment by Galadirith** [comment]
On demand sync is now in master with `2.0.0` to be released imminently. I will leave this issue open for discussion on automatic sync with scroll.

**Comment by KazWolfe** [comment]
I would definitely love to have automatic scroll sync builtin. I like using Markdown to take notes in class, and having the live preview update would just be amazing. +1

**Comment by lierdakil** [comment]
A bit of a band-aid, that is to say, automatic sync on change, implemented in v3.0.1.
